-- Nova 系统模块基础表（H2 PostgreSQL 模式 / PostgreSQL / 金仓 / openGauss 通用语法）

create table if not exists sys_user (
    id          bigint generated by default as identity primary key,
    tenant_id   bigint       default 0,
    username    varchar(64)  not null,
    password    varchar(128) not null,
    nickname    varchar(64),
    mobile      varchar(256),
    status      int          default 1,
    deleted     int          default 0,
    create_by   bigint,
    create_time timestamp,
    update_by   bigint,
    update_time timestamp
);
create unique index if not exists uk_sys_user_username on sys_user (username);

create table if not exists sys_role (
    id          bigint generated by default as identity primary key,
    tenant_id   bigint      default 0,
    role_code   varchar(64) not null,
    role_name   varchar(64),
    deleted     int         default 0,
    create_by   bigint,
    create_time timestamp,
    update_by   bigint,
    update_time timestamp
);

create table if not exists sys_user_role (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id)
);
